apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: icap-client-main
  name: frontend-icap-lb
spec:
  type: LoadBalancer
  ports:
  - name: icap-port
    port: 1344
    targetPort: 1344
  - name: mvp-icap-service
    port: 1345
    targetPort: 1345
  selector:
    app: adaptation
