apiVersion: v1
kind: Service
metadata:
  name: icap-service
  namespace: {{.Values.adaptationservice.namespace}}
  labels:
    app: {{ .Values.icapservice.applabel }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.icapservice.applabel }}
  # The node port is hard coded to match the load balancer. In the future we want to be template it.
  ports:
  - port: 1344
    protocol: TCP
    name: openport
    targetPort: 1344
  - port: 1345
    protocol: TCP
    nodePort: 32323
    name: tlsport
    targetPort: 1345
