apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: {{ .Values.podjanitor.name }}
  name: {{ .Values.podjanitor.name }}
  namespace: {{ .Values.podjanitor.namespace }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
     metadata:
       labels:
         app: {{ .Values.podjanitor.name }}
     spec:
      template:
        metadata:
          labels:
            app: {{ .Values.podjanitor.name }}
        spec:
          serviceAccountName: {{ .Values.serviceAccount.janitorname }}
          containers:
          - name: pod-janitor
            image: {{ .Values.imagestore.podjanitor.repository }}:{{ .Values.imagestore.podjanitor.tag }}
            args:
            - --pod-namespace={{ .Values.podjanitor.namespace }}
            - --delete-successful-after={{ .Values.podjanitor.deleteSuccessfulAfter }}
            - --delete-failed-after={{ .Values.podjanitor.deleteFailedAfter }}
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 10m
                memory: 10Mi
          restartPolicy: OnFailure 