apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: {{ .Values.podjanitor.name }}
  name: {{ .Values.podjanitor.name }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
     metadata:
       labels:
         app: {{ .Values.podjanitor.name }}
     spec:
      template:
        metadata:
          labels:
            app: {{ .Values.podjanitor.name }}
        spec:
          serviceAccountName: {{ .Values.serviceAccount.janitorname }}
          containers:
            - name: pod-janitor
              image: {{ .Values.imagestore.podjanitor.registry }}{{ .Values.imagestore.podjanitor.repository }}:{{ .Values.imagestore.podjanitor.tag }}
              args:
              - --pod-namespace={{ .Release.Namespace }}
              - --delete-successful-after={{ .Values.podjanitor.deleteSuccessfulAfter }}
              - --delete-failed-after={{ .Values.podjanitor.deleteFailedAfter }}
              - --pushgateway-endpoint={{ .Values.prometheus.pushgatewayendpoint }}
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 10m
                  memory: 10Mi
          imagePullSecrets:
            - name: adaptation-registry-credential
          restartPolicy: OnFailure