apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels: 
    app: {{ .Values.rabbitmqService.app }}
    component: {{ .Values.rabbitmqService.component }}
  name: {{ .Values.rabbitmqService.name }}
spec:
 replicas: 3
{{- if .Values.imagestore.rabbitmq }} 
 image: "{{ .Values.imagestore.rabbitmq.registry }}{{ .Values.imagestore.rabbitmq.repository }}:{{ .Values.imagestore.rabbitmq.tag }}"
 imagePullSecrets:
  - name: rabbitmq-service-registry-credential
{{- end }}     
 affinity:
   podAntiAffinity:
     preferredDuringSchedulingIgnoredDuringExecution: 
     - weight: 100  
       podAffinityTerm:
         labelSelector:
          matchExpressions:
          - key: {{ .Values.rabbitmqService.key }}
            operator: In
            values:
            - store
         topologyKey: kubernetes.io/hostname
 resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 2Gi
 persistence:
   storageClassName: azurefile
   storage: 10Gi
