{{- if .Values.secrets }}
# This secret is required to create the Rebuild processing pod. It is referenced directly in the code.
apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: {{ .Values.secrets.containerregistry.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end }}