apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Values.transactionstore.shareName }}
spec:
  capacity:
    storage: {{ .Values.transactionstore.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be removed in pvc deletion
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict  # https://linux.die.net/man/8/mount.cifs
    - nosharesock
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: {{ template "transactionqueryservice.fullname" . }}  # make sure it's a unique id in the cluster
    volumeAttributes:
      resourceGroup: {{ .Values.transactionstore.resourceGroup }}  # optional, only set this when storage account is not in the same resource group as agent node
      storageAccount: {{ .Values.transactionstore.storageAccount }}
      shareName: {{ .Values.transactionstore.shareName }}  # only file share name, don't use full path
    nodeStageSecretRef:
      name: transactionstoresecret
      namespace: {{ .Release.Namespace }}