{{- if .Values.fluentd.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: icap-adaptation
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: "{{ .Values.imagestore.fluentd.registry }}{{ .Values.imagestore.fluentd.repository }}:{{ .Values.imagestore.fluentd.tag }}"
        env:
          {{- if .Values.fluentd.elasticsearchhost }}
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: {{ .Values.fluentd.elasticsearchhost }}
          {{- end }}
          {{- if .Values.fluentd.elasticsearchport }}
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: {{ .Values.fluentd.elasticsearchport }}
          {{- end }}
          {{- if .Values.fluentd.elasticsearchscheme }}
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: {{ .Values.fluentd.elasticsearchscheme }}
          {{- end }}
          # Option to configure elasticsearch plugin with self signed certs
          # ================================================================
          {{- if .Values.fluentd.elasticsearchsslverify }}
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: {{ .Values.fluentd.elasticsearchsslverify }}
          {{- end }}
          # Option to configure elasticsearch plugin with tls
          # ================================================================
          {{- if .Values.fluentd.elasticsearchsslversion }}
          - name: FLUENT_ELASTICSEARCH_SSL_VERSION
            value: {{ .Values.fluentd.elasticsearchsslversion }}
          {{- end }}
          # X-Pack Authentication
          # =====================
          {{- if .Values.fluentd.elasticsearchuser }}
          - name: FLUENT_ELASTICSEARCH_USER
            value: {{ .Values.fluentd.elasticsearchuser }}      
          {{- end }}
          {{- if .Values.fluentd.elasticsearchpassword }}
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: {{ .Values.fluentd.elasticsearchpassword }}
          {{- end }}
          {{- if .Values.fluentd.systemdconf }}
          - name: FLUENTD_SYSTEMD_CONF
            value: {{ .Values.fluentd.systemdconf }}
          {{- end }}
        resources:
{{ toYaml .Values.fluentd.resources | indent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
{{- end }}
