apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.managementui.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.managementui.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.managementui.deployment.name }}
    spec:
      containers:
        - name: icap-managementui
          image: {{ .Values.imagestore.icapmanagementui.registry }}{{ .Values.imagestore.icapmanagementui.repository }}:{{ .Values.imagestore.icapmanagementui.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: TRANSACTION_EVENT_API_URL
              value: {{ .Values.managementui.config.transactionEventApiUrl }}
            - name: POLICY_MANAGEMENT_API_URL
              value: {{ .Values.managementui.config.policyManagementApiUrl }}         
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0" 
          ports:
            - containerPort: {{ .Values.managementui.deployment.port }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: management-ui-registry-credential
