{
 "title": "Icap-Adaptation / App_Metrics ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Icap-Server-Monit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gw_icap_server_children_number", "legendFormat": "icap_server_children_number" }
   ]
  },
  {
   "title": "Icap-Server-Monit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gw_icap_server_free_servers", "legendFormat": "icap_server_free_servers" }
   ]
  },
  {
   "title": "Icap-Server-Monit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gw_icap_server_used_servers", "legendFormat": "icap_server_used_servers" }
   ]
  },
  {
   "title": "Icap-Server-Monit",
   "type": "graph",
   "description": "Icap-server-monit",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gw_icap_server_used_servers", "legendFormat": "icap-server-used-servers" },
    { "expr": "gw_icap_server_children_number", "legendFormat": "icap-server-children-number" },
    {
     "expr": "gw_icap_server_closed_processes",
     "legendFormat": "icap-server-closed-processes"
    },
    { "expr": "gw_icap_server_free_servers", "legendFormat": "gw_icap_server_free_servers" },
    {
     "expr": "gw_icap_server_crashed_processes",
     "legendFormat": "icap-server-crashed-processes"
    },
    {
     "expr": "gw_icap_server_started_processes",
     "legendFormat": "icap-server-starte-processes"
    }
   ]
  },
  {
   "title": "Total Icap Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gw_rebuild_reqmods", "legendFormat": "GW_REQMOD" },
    { "expr": "gw_rebuild_respmods", "legendFormat": "GW_RESPMOD" }
   ]
  },
  {
   "title": "icap-Safe",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(gw_rebuild_scan_rebuilt)", "legendFormat": "ICAP-SAFE" }
   ]
  },
  {
   "title": "Total File Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gw_rebuild_requests_scanned", "legendFormat": "TOTAL_FILE_PROCESSED" }
   ]
  },
  {
   "title": "Blocked By NCFS & Blocked By Policy [Blocked]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gw_rebuild_rebuild_failures", "legendFormat": "BLOCKED" }
   ]
  }
 ]
}