{
 "title": "Icap-App-Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Icap-Server-Monit",
   "type": "graph",
   "description": "Icap-server-monit",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gw_icap_server_used_servers", "legendFormat": "icap-server-used-servers" },
    { "expr": "gw_icap_server_children_number", "legendFormat": "icap-server-children-number" },
    {
     "expr": "gw_icap_server_closed_processes",
     "legendFormat": "icap-server-closed-processes"
    },
    { "expr": "gw_icap_server_free_servers", "legendFormat": "gw_icap_server_free_servers" },
    {
     "expr": "gw_icap_server_crashed_processes",
     "legendFormat": "icap-server-crashed-processes"
    },
    {
     "expr": "gw_icap_server_started_processes",
     "legendFormat": "icap-server-starte-processes"
    }
   ]
  },
  {
   "title": "Total Icap Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gw_rebuild_reqmods", "legendFormat": "GW_REQMOD" },
    { "expr": "gw_rebuild_respmods", "legendFormat": "GW_RESPMOD" }
   ]
  },
  {
   "title": "icap-Safe",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(gw_rebuild_scan_rebuilt)", "legendFormat": "ICAP-SAFE" }
   ]
  },
  {
   "title": "Total File Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gw_rebuild_requests_scanned", "legendFormat": "TOTAL_FILE_PROCESSED" }
   ]
  },
  {
   "title": "Blocked By NCFS & Blocked By Policy [Blocked]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gw_rebuild_rebuild_failures", "legendFormat": "BLOCKED" }
   ]
  }
 ]
}