{
 "title": "Icap-Adaptation / App_Metrics /V1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total File Processed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "gw_rebuild_requests_scanned", "legendFormat": "TOTAL_FILE_PROCESSED" }
   ]
  },
  {
   "title": "Total Icap Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(gw_rebuild_reqmods) + (gw_rebuild_respmods)",
     "legendFormat": "TOTAL_Request"
    }
   ]
  },
  {
   "title": "Safe",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "gw_rebuild_scan_rebuilt", "legendFormat": "Safe" }
   ]
  },
  {
   "title": "Total Icap Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(gw_rebuild_reqmods) + (gw_rebuild_respmods) ",
     "legendFormat": "Total_Request"
    }
   ]
  },
  {
   "title": "icap-Safe",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "(gw_rebuild_scan_rebuilt)", "legendFormat": "ICAP-SAFE" }
   ]
  },
  {
   "title": "Total File Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gw_rebuild_requests_scanned", "legendFormat": "TOTAL_FILE_PROCESSED" }
   ]
  },
  {
   "title": "Blocked By NCFS & Blocked By Policy [Blocked]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gw_rebuild_rebuild_failures", "legendFormat": "BLOCKED" }
   ]
  }
 ]
}