{
 "title": "Icap-Adaptation / App_Metrics ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running_Server_Statistics",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gw_icap_server_children_number", "legendFormat": "icap_server_children_number" }
   ]
  },
  {
   "title": "Running_Server_Statistics",
   "type": "gauge",
   "description": "Icap Running_Server_Statistics",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gw_icap_server_free_servers", "legendFormat": "icap_server_free_servers" }
   ]
  },
  {
   "title": "Running_Server_Statistics",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gw_icap_server_used_servers", "legendFormat": "icap_server_used_servers" }
   ]
  },
  {
   "title": "Running_Server_Statistics",
   "type": "bargauge",
   "description": "Running_Server_Statistics",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gw_icap_server_used_servers", "legendFormat": "icap-server-used-servers" },
    { "expr": "gw_icap_server_children_number", "legendFormat": "icap-server-children-number" },
    {
     "expr": "gw_icap_server_closed_processes",
     "legendFormat": "icap-server-closed-processes"
    },
    { "expr": "gw_icap_server_free_servers", "legendFormat": "icap_server_free_servers" },
    {
     "expr": "gw_icap_server_crashed_processes",
     "legendFormat": "icap-server-crashed-processes"
    },
    {
     "expr": "gw_icap_server_started_processes",
     "legendFormat": "icap-server-starte-processes"
    }
   ]
  },
  {
   "title": "gw_rebuild Statistics: Requests Rebuilt",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gw_rebuild_requests_scanned", "legendFormat": "Requests Scanned" },
    { "expr": "gw_rebuild_rebuild_failures", "legendFormat": "Rebuild Failures" },
    { "expr": "gw_rebuild_rebuild_errors", "legendFormat": "Rebuild Errors" },
    { "expr": "gw_rebuild_scan_rebuilt", "legendFormat": "Scans Rebuilt" }
   ]
  },
  {
   "title": "Total Icap Requests(SUM OF All Value)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "gw_rebuild_reqmods", "legendFormat": "GW_REQMOD" },
    { "expr": "gw_rebuild_respmods", "legendFormat": "GW_RESPMOD" }
   ]
  },
  {
   "title": "Total Icap Requests (Average Value): Request",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gw_rebuild_reqmods", "legendFormat": "GW_REQMOD" },
    { "expr": "gw_rebuild_respmods", "legendFormat": "GW_RESPMOD" },
    { "expr": "gw_rebuild_unprocessed", "legendFormat": "Unprocessed" },
    { "expr": "gw_rebuild_unprocessable", "legendFormat": "Unprocessable" }
   ]
  },
  {
   "title": "Total File Processed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "gw_rebuild_requests_scanned", "legendFormat": "TOTAL_FILE_PROCESSED" }
   ]
  },
  {
   "title": "Icap-Safe (Scans Rebuilt )",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "gw_rebuild_scan_rebuilt", "legendFormat": "ICAP-SAFE " }
   ]
  },
  {
   "title": "Blocked By NCFS & Blocked By Policy [Blocked]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gw_rebuild_rebuild_failures", "legendFormat": "BLOCKED" }
   ]
  }
 ]
}