apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-userstore
  labels:
    usage: pv-userstore
spec:
  capacity:
    storage: {{ .Values.identitymanagementservice.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  azureFile:
    secretName: userstoresecret
    shareName: {{ .Values.identitymanagementservice.shareName }}
    readOnly: false