{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nginx.fullname" . }}
data:
  nginx.conf: |-
    events {}
    http {
        client_max_body_size 0;
        server {
            location / {
                proxy_pass http://{{ .Values.filedropui.service.name }}/;
            }
            location /api {
                proxy_pass http://{{ .Values.filedropapi.service.name }};
            }
        }
    }