apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: file-drop-ui
  name: {{ .Values.nginx.service.name }}
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    {{- include "nginx.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.deployment.port }}